services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strava_mcp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
volumes:
    pgdata: